"""Add description field to Medicine

Revision ID: 144329d937b3
Revises: 
Create Date: 2023-11-19 19:57:53.760245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '144329d937b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Medicine', sa.Column('description', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Medicine', 'description')
    # ### end Alembic commands ###
