"""Add working_time column to Pharmacy model

Revision ID: 4bc62915bfdb
Revises: 144329d937b3
Create Date: 2023-11-19 20:20:25.120824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bc62915bfdb'
down_revision = '144329d937b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Pharmacy', sa.Column('working_time', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Pharmacy', 'working_time')
    # ### end Alembic commands ###
