"""Add extra_data field to models

Revision ID: 85427cc28b3b
Revises: 4bc62915bfdb
Create Date: 2023-12-10 12:28:32.853646

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '85427cc28b3b'
down_revision = '4bc62915bfdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Availability', sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('Availability', sa.Column('medicine_quantity_per_package', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Availability', 'Medicine', ['medicine_quantity_per_package'], ['quantity_per_package'])
    op.add_column('Medicine', sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('Pharmacy', sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Pharmacy', 'extra_data')
    op.drop_column('Medicine', 'extra_data')
    op.drop_constraint(None, 'Availability', type_='foreignkey')
    op.drop_column('Availability', 'medicine_quantity_per_package')
    op.drop_column('Availability', 'extra_data')
    # ### end Alembic commands ###
